### ISSUE TITLE
Warning:

### ISSUE THREAD

**Issue by MarshMeadow** [BetaLeaf/PortableApps-App-Creation-Wizard#1]
![Warning](https://user-images.githubusercontent.com/88599122/128636644-13539e2a-1b19-4894-91d6-9d930656aeef.PNG)

**Comment by MarshMeadow** [comment]
Nevermind it works, you just need to click on ignore.

**Comment by AetherCollective** [comment]
This program is intended to work properly only when installed inside the PortableApps.com Platform Launcher and it also depends on a few other portable apps.

### **This software is abandoned** and improvements/fixes won't be made to them, not at least by me. I ended up remaking this app from scratch, massively speeding up app creation by simplifying it, but at the same time removes some customizability options in favor for more automatic ones. If you are interested in giving that one a go, see the attachment below.

[ProjPortable.zip](https://github.com/EmilyLove26/PortableApps-App-Creation-Wizard/files/6952097/ProjPortable.zip)
