### ISSUE TITLE
About that file that you sent me:

### ISSUE THREAD

**Issue by MarshMeadow** [BetaLeaf/PortableApps-App-Creation-Wizard#2]
The "ProjPortable.7z" file that you sent me I can't open it, it wants me to use something to open it. It's a ".7z" file which I've never heard of before.

**Comment by MarshMeadow** [comment]
Actually, I could possibly be wrong about never hearing about the ".7z" file.

**Comment by skycommand** [comment]
`.7z` is the most famous archive format since 2010. You can open it with [7-Zip](https://www.7-zip.org/). The PortableApps platform extensively uses it.

Of course, you could have Googled ".7z". And you could have placed this response under the same thread that you opened earlier.

**Comment by MarshMeadow** [comment]
Thanks.
